/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-10-13 07:37:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1696227266456L));
    _jspx_dependants.put("jar:file:/E:/apache-maven-3.9.4/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\" data-bs-theme=\"white\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>SIK</title>\r\n");
      out.write("<!-- js -->\r\n");
      out.write("<script src=\"/sik/resources/common/js/jquery-3.7.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"https://getbootstrap.com/docs/5.3/assets/css/docs.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"canonical\"\r\n");
      out.write("	href=\"https://getbootstrap.com/docs/5.3/examples/headers/\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/@docsearch/css@3\">\r\n");
      out.write("<link href=\"/sik/resources/common/css/font.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/sik/resources/common/css/header.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("	font-size: 1.125rem;\r\n");
      out.write("	text-anchor: middle;\r\n");
      out.write("	-webkit-user-select: none;\r\n");
      out.write("	-moz-user-select: none;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("	.bd-placeholder-img-lg {\r\n");
      out.write("		font-size: 3.5rem;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-divider {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 3rem;\r\n");
      out.write("	background-color: rgba(0, 0, 0, .1);\r\n");
      out.write("	border: solid rgba(0, 0, 0, .15);\r\n");
      out.write("	border-width: 1px 0;\r\n");
      out.write("	box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em\r\n");
      out.write("		rgba(0, 0, 0, .15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b-example-vr {\r\n");
      out.write("	flex-shrink: 0;\r\n");
      out.write("	width: 1.5rem;\r\n");
      out.write("	height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi {\r\n");
      out.write("	vertical-align: -.125em;\r\n");
      out.write("	fill: currentColor;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	z-index: 2;\r\n");
      out.write("	height: 2.75rem;\r\n");
      out.write("	overflow-y: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-scroller .nav {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: nowrap;\r\n");
      out.write("	padding-bottom: 1rem;\r\n");
      out.write("	margin-top: -1px;\r\n");
      out.write("	overflow-x: auto;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	-webkit-overflow-scrolling: touch;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-bd-primary { -\r\n");
      out.write("	-bd-violet-bg: #712cf9; -\r\n");
      out.write("	-bd-violet-rgb: 112.520718, 44.062154, 249.437846; -\r\n");
      out.write("	-bs-btn-font-weight: 600; -\r\n");
      out.write("	-bs-btn-color: var(- -bs-white); -\r\n");
      out.write("	-bs-btn-bg: var(- -bd-violet-bg); -\r\n");
      out.write("	-bs-btn-border-color: var(- -bd-violet-bg); -\r\n");
      out.write("	-bs-btn-hover-color: var(- -bs-white); -\r\n");
      out.write("	-bs-btn-hover-bg: #6528e0; -\r\n");
      out.write("	-bs-btn-hover-border-color: #6528e0; -\r\n");
      out.write("	-bs-btn-focus-shadow-rgb: var(- -bd-violet-rgb); -\r\n");
      out.write("	-bs-btn-active-color: var(- -bs-btn-hover-color); -\r\n");
      out.write("	-bs-btn-active-bg: #5a23c8; -\r\n");
      out.write("	-bs-btn-active-border-color: #5a23c8;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bd-mode-toggle {\r\n");
      out.write("	z-index: 1500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	z-index: 99;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".col {\r\n");
      out.write("	font-family: \"NanumGothicB\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header class=\"p-3 mb-3 border-bottom small shadow\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div\r\n");
      out.write("				class=\"d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start\"\r\n");
      out.write("				style=\"gap: 50px\">\r\n");
      out.write("				<a href=\"#\"\r\n");
      out.write("					class=\"d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none\">\r\n");
      out.write("					<img src=\"/sik/resources/common/images/siklogo.png\" width=\"40\"\r\n");
      out.write("					style=\"magin-left: 30px\">\r\n");
      out.write("				</a>\r\n");
      out.write("				<ul\r\n");
      out.write("					class=\"nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0\">\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("						data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasSupport\">지원</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("						data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasInventory\">재고</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("						data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasFranchisee\">관리</a>\r\n");
      out.write("					</li>\r\n");
      out.write("\r\n");
      out.write("					<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
      out.write("						data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasPromotion\">홍보</a>\r\n");
      out.write("					</li>\r\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("				<a href=\"/sik/views/common/profile.jsp\"> <img\r\n");
      out.write("					src=\"/sik/resources/common/images/profile.png\" alt=\"mdo\" width=\"32\"\r\n");
      out.write("					height=\"32\" class=\"rounded-circle\" />프로필\r\n");
      out.write("				</a>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- canvas 생성 -->\r\n");
      out.write("	<!-- 지원 -->\r\n");
      out.write("	<div class=\"offcanvas offcanvas-start small shadow\"\r\n");
      out.write("		data-bs-scroll=\"true\" data-bs-backdrop=\"false\" tabindex=\"-1\"\r\n");
      out.write("		id=\"offcanvasSupport\" aria-labelledby=\"offcanvasSupportLabel\">\r\n");
      out.write("		<div class=\"offcanvas-header\">\r\n");
      out.write("			<h5 class=\"offcanvas-title\" id=\"offcanvasSupportLabel\">지원</h5>\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"offcanvas-body\">\r\n");
      out.write("			<div class=\"dropdown mt-3\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("						<!-- 1 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("									브랜드 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">브랜드 추가</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">브랜드 조회</a><br>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\"\r\n");
      out.write("									aria-expanded=\"true\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("									메뉴 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">레시피 등록</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">레시피 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">레시피 수정</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">레시피 삭제</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\"\r\n");
      out.write("										data-bs-target=\"#flush-collapseThree\" aria-expanded=\"true\"\r\n");
      out.write("										aria-controls=\"flush-collapseThree\">발주 확인</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"flush-collapseThree\"\r\n");
      out.write("									class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">종합 발주 확인</a><br>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("										aria-expanded=\"true\" aria-controls=\"collapseFour\">생산업체\r\n");
      out.write("										관리</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"collapseFour\" class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">생산업체 등록</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">생산업체 조회</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">생산요청 등록</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">생산요청 조회</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 재고 -->\r\n");
      out.write("	<div class=\"offcanvas offcanvas-start small shadow\"\r\n");
      out.write("		data-bs-scroll=\"true\" data-bs-backdrop=\"false\" tabindex=\"-1\"\r\n");
      out.write("		id=\"offcanvasInventory\" aria-labelledby=\"offcanvasInventoryLabel\">\r\n");
      out.write("		<div class=\"offcanvas-header\">\r\n");
      out.write("			<h5 class=\"offcanvas-title\" id=\"offcanvasInventoryLabel\">재고</h5>\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"offcanvas-body\">\r\n");
      out.write("			<div class=\"dropdown mt-3\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("						<!-- 1 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("									매장별 재고 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">브랜드 재고 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">매장별 재고 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">상품별 재고 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\"\r\n");
      out.write("									aria-expanded=\"true\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("									본사 재고 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">브랜드 재고 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">상품별 재고 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\"\r\n");
      out.write("										data-bs-target=\"#flush-collapseThree\" aria-expanded=\"true\"\r\n");
      out.write("										aria-controls=\"flush-collapseThree\">메뉴3</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"flush-collapseThree\"\r\n");
      out.write("									class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">메뉴1</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴2</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("										aria-expanded=\"true\" aria-controls=\"collapseFour\">메뉴4</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"collapseFour\" class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"#\">메뉴1</a><br> <a href=\"#\">메뉴2</a><br> <a\r\n");
      out.write("											href=\"#\">메뉴3</a><br> <a href=\"#\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 관리 -->\r\n");
      out.write("	<div class=\"offcanvas offcanvas-start small shadow\"\r\n");
      out.write("		data-bs-scroll=\"true\" data-bs-backdrop=\"false\" tabindex=\"-1\"\r\n");
      out.write("		id=\"offcanvasFranchisee\" aria-labelledby=\"offcanvasFranchiseeLabel\">\r\n");
      out.write("		<div class=\"offcanvas-header\">\r\n");
      out.write("			<h5 class=\"offcanvas-title\" id=\"offcanvasFranchiseeLabel\">관리</h5>\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"offcanvas-body\">\r\n");
      out.write("			<div class=\"dropdown mt-3\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("						<!-- 1 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("									브랜드 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">브랜드 공지 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">브랜드 공지 관리</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\"\r\n");
      out.write("									aria-expanded=\"true\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("									계약관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">계약현황조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">계약 수정</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">계약현황검색</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">계약등록</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\"\r\n");
      out.write("										data-bs-target=\"#flush-collapseThree\" aria-expanded=\"true\"\r\n");
      out.write("										aria-controls=\"flush-collapseThree\">매장현황</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"flush-collapseThree\"\r\n");
      out.write("									class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">메출필터검색</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매출조회</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매출전표</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">전국매장</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매장검색</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("										aria-expanded=\"true\" aria-controls=\"collapseFour\">가맹점관리\r\n");
      out.write("									</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"collapseFour\" class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">매장상세</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매장관리정검</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매장요청사항</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">매장요청조회</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 홍보 -->\r\n");
      out.write("	<div class=\"offcanvas offcanvas-start small shadow\"\r\n");
      out.write("		data-bs-scroll=\"true\" data-bs-backdrop=\"false\" tabindex=\"-1\"\r\n");
      out.write("		id=\"offcanvasPromotion\" aria-labelledby=\"offcanvasPromotionLabel\">\r\n");
      out.write("		<div class=\"offcanvas-header\">\r\n");
      out.write("			<h5 class=\"offcanvas-title\" id=\"offcanvasPromotionLabel\">홍보</h5>\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"offcanvas-body\">\r\n");
      out.write("			<div class=\"dropdown mt-3\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("						<!-- 1 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("									메뉴반응</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">브랜드 메뉴 반응</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴 반응</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\"\r\n");
      out.write("									aria-expanded=\"true\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("									프로모션 현황</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">프로모션 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">프로모션 등록</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">프로모션 수정</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\"\r\n");
      out.write("										data-bs-target=\"#flush-collapseThree\" aria-expanded=\"true\"\r\n");
      out.write("										aria-controls=\"flush-collapseThree\">광고 현황</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"flush-collapseThree\"\r\n");
      out.write("									class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">광고 조회</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">광고 등록</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">광고 수정</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("										aria-expanded=\"true\" aria-controls=\"collapseFour\">평판</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"collapseFour\" class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">브랜드 평판</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴 평판</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- admin -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"offcanvas offcanvas-start small shadow\"\r\n");
      out.write("		data-bs-scroll=\"true\" data-bs-backdrop=\"false\" tabindex=\"-1\"\r\n");
      out.write("		id=\"offcanvasAdmin\" aria-labelledby=\"offcanvasAdminLabel\">\r\n");
      out.write("		<div class=\"offcanvas-header\">\r\n");
      out.write("			<h5 class=\"offcanvas-title\" id=\"offcanvasAdminLabel\">admin</h5>\r\n");
      out.write("			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("				aria-label=\"Close\"></button>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"offcanvas-body\">\r\n");
      out.write("			<div class=\"dropdown mt-3\">\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col\">\r\n");
      out.write("					<div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("						<!-- 1 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\"\r\n");
      out.write("									aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("									직원 조회</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">직원조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">직급별 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">부서별 조회</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- 2 -->\r\n");
      out.write("						<div class=\"accordion-item\">\r\n");
      out.write("							<h2 class=\"accordion-header\">\r\n");
      out.write("								<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("									data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\"\r\n");
      out.write("									aria-expanded=\"true\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("									직원 관리</button>\r\n");
      out.write("							</h2>\r\n");
      out.write("							<div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\"\r\n");
      out.write("								data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("								<div class=\"accordion-body\">\r\n");
      out.write("									<a href=\"/sik/views/main.jsp\">직원 정보 등록</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">직원 정보 수정</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">직원 정보 삭제</a><br> <a\r\n");
      out.write("										href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 3 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\"\r\n");
      out.write("										data-bs-target=\"#flush-collapseThree\" aria-expanded=\"true\"\r\n");
      out.write("										aria-controls=\"flush-collapseThree\">메뉴3</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"flush-collapseThree\"\r\n");
      out.write("									class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">메뉴1</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴2</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- 4 -->\r\n");
      out.write("							<div class=\"accordion-item\">\r\n");
      out.write("								<h2 class=\"accordion-header\">\r\n");
      out.write("									<button class=\"accordion-button collapsed\" type=\"button\"\r\n");
      out.write("										data-bs-toggle=\"collapse\" data-bs-target=\"#collapseFour\"\r\n");
      out.write("										aria-expanded=\"true\" aria-controls=\"collapseFour\">메뉴4</button>\r\n");
      out.write("								</h2>\r\n");
      out.write("								<div id=\"collapseFour\" class=\"accordion-collapse collapse\"\r\n");
      out.write("									data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("									<div class=\"accordion-body\">\r\n");
      out.write("										<a href=\"/sik/views/main.jsp\">메뉴1</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴2</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴3</a><br> <a\r\n");
      out.write("											href=\"/sik/views/main.jsp\">메뉴4</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- END -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- admin -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(156,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty sessionScope.loginMember and sessionScope.loginMember.adminYn eq 'Y' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"\r\n");
          out.write("							data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasAdmin\">admin</a>\r\n");
          out.write("						</li>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
